// <auto-generated />
namespace DejtingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProfileView_and_Image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfileView_and_Image));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071125009_ProfileView_and_Image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
