// <auto-generated />
namespace DejtingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageNew20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageNew20));
        
        string IMigrationMetadata.Id
        {
            get { return "202001071143137_ImageNew2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
